image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
  - docker build -t $IMAGE_NAME .
  - docker push $IMAGE_NAME
